### ISSUE TITLE
ERROR: Parsing halted due to errors, see error messages above

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#18]
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
ERROR: ExpansionError during parsing /home/elhawary/p3/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugins.bb
Traceback (most recent call last):
  File "/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1217, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f59f084fb20>, d=<bb.data_smart.DataSmart object at 0x7f59f0b102e0>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1627, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f59f084fb20>, d=<bb.data_smart.DataSmart object at 0x7f59f0b102e0>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 746, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f59f084fb20>, d=<bb.data_smart.DataSmart object at 0x7f59f0b102e0>, name='default'):
     
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 729, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f59f084fb20>, d=<bb.data_smart.DataSmart object at 0x7f59f0b102e0>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 932, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python3-native:/home/elhawary/p3/openpli-dreambox-oe-core/openembedded-core/scripts:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/bin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/elhawary"; git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false -c core.pager=cat ls-remote https://github.com/Hains/enigma2-plugins.git ', d=<bb.data_smart.DataSmart object at 0x7f59f084feb0>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/python3-native:/home/elhawary/p3/openpli-dreambox-oe-core/openembedded-core/scripts:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/mipsel-oe-linux:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/enigma2-plugins/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/elhawary/p3/openpli-dreambox-oe-core/bitbake/bin:/home/elhawary/p3/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/elhawary"; git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false -c core.pager=cat ls-remote https://github.com/Hains/enigma2-plugins.git  failed with exit code 128, output:
fatal: could not read Username for 'https://github.com': No such device or address

The variable dependency chain for the failure is: SRCPV -> PV -> BP -> FILESPATH

ERROR: Parsing halted due to errors, see error messages above

**Comment by fairbird** [comment]
This is not error compile not core error also ...
It is from your internet (some time can not connect with some url of some recipes)
Just wait 5 minutes and try again !!

**Comment by fairbird** [comment]
Solved !!
https://github.com/fairbird/openpli-dreambox-oe-core/commit/20adfcf1564af21e0f77fdba460b2624f04eb372
