### ISSUE TITLE
WeatherInfo.

### ISSUE THREAD

**Issue by 68foxboris** [fairbird/openpli-dreambox-oe-core#39]
Good afternoon.Have you tried installing this weather plugin-https://github.com/openatv/WeatherInfo
I can not enter the application menu and there is an error in the log.
`
2023-03-10 12:08:08.5802 [Weatherinfo] MSN successfully accessed..
2023-03-10 12:08:08.5849 Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
	    
	  File "/usr/lib/python3.11/threading.py", line 975, in run
	    
	  File "/usr/lib/python3.11/site-packages/twisted/_threads/_threadworker.py", line 47, in work
	    
	  File "/usr/lib/python3.11/site-packages/twisted/_threads/_team.py", line 182, in doWork
	    
	--- <exception caught here> ---
	  File "/usr/lib/python3.11/site-packages/twisted/python/threadpool.py", line 244, in inContext
	    
	  File "/usr/lib/python3.11/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
	    
	  File "/usr/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
	    
	  File "/usr/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
	    
	  File "/home1/master/openpli-oe-core/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/enigma2-tools-weatherinfo/1.7+gitAUTOINC+7560d977d8-r0/image/usr/lib/enigma2/python/Tools/Weatherinfo.py", line 352, in msnparser
	    
	  File "/home1/master/openpli-oe-core/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/enigma2-plugin-extensions-oaweather/gitAUTOINC+046b399d9e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OAWeather/plugin.py", line 266, in refreshWeatherDataCallback
	    
	  File "/home1/master/openpli-oe-core/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/enigma2-plugin-extensions-oaweather/gitAUTOINC+046b399d9e-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OAWeather/plugin.py", line 194, in writeData
	    
	builtins.OverflowError: Python int too large to convert to C long

`
![1_0_16_330_8_70_1680000_0_0_0_20230310120843](https://user-images.githubusercontent.com/17230642/224291027-232d6fc2-0f80-42e2-bbea-312bd9d99f84.jpg)

**Comment by fairbird** [comment]
You should be to send crash log to the owner plugin not here ...
 The owner plugin should be to fix plugin not to fix core !!!

**Comment by 68foxboris** [comment]
This is understandable but it works on OE-A. Plugin with git https://github.com/oe-alliance/OAWeather

**Comment by fairbird** [comment]
My core is much newer than Source OE-A ... I use python 3.11.1 and OE-A master branch still using python 3.11.0.
