### ISSUE TITLE
make: *** [Makefile:113: feed] Error 1

### ISSUE THREAD

**Issue by elhawaryna** [fairbird/openpli-dreambox-oe-core#44]
check internet connection: Online      
NOTE: Reconnecting to bitbake server...
NOTE: No reply from server in 30s
NOTE: Retrying server connection (#1)... (22:41:25.945510)
NOTE: Reconnecting to bitbake server...
NOTE: No reply from server in 30s
NOTE: Retrying server connection (#2)... (22:42:26.001524)
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#3)... (Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/main.py", line 487, in setup_bitbake
    server_connection = bb.server.process.connectProcessServer(sockname, featureset)
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/server/process.py", line 686, in connectProcessServer
    sock.connect(os.path.basename(sockname))
BlockingIOError: [Errno 11] Resource temporarily unavailable
, 22:42:26.097297)
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#4)... (Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/main.py", line 487, in setup_bitbake
    server_connection = bb.server.process.connectProcessServer(sockname, featureset)
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/server/process.py", line 686, in connectProcessServer
    sock.connect(os.path.basename(sockname))
BlockingIOError: [Errno 11] Resource temporarily unavailable
, 22:42:26.097871)
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#5)... (Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/main.py", line 487, in setup_bitbake
    server_connection = bb.server.process.connectProcessServer(sockname, featureset)
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/server/process.py", line 686, in connectProcessServer
    sock.connect(os.path.basename(sockname))
BlockingIOError: [Errno 11] Resource temporarily unavailable
, 22:42:31.101923)
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#6)... (Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/main.py", line 487, in setup_bitbake
    server_connection = bb.server.process.connectProcessServer(sockname, featureset)
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/server/process.py", line 686, in connectProcessServer
    sock.connect(os.path.basename(sockname))
BlockingIOError: [Errno 11] Resource temporarily unavailable
, 22:42:36.105883)
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#7)... (Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/main.py", line 487, in setup_bitbake
    server_connection = bb.server.process.connectProcessServer(sockname, featureset)
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/server/process.py", line 686, in connectProcessServer
    sock.connect(os.path.basename(sockname))
BlockingIOError: [Errno 11] Resource temporarily unavailable
, 22:42:41.109910)
NOTE: Reconnecting to bitbake server...
NOTE: Retrying server connection (#8)... (Traceback (most recent call last):
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/main.py", line 487, in setup_bitbake
    server_connection = bb.server.process.connectProcessServer(sockname, featureset)
  File "/home/elhawary/openpli-dreambox-oe-core/bitbake/lib/bb/server/process.py", line 686, in connectProcessServer
    sock.connect(os.path.basename(sockname))
BlockingIOError: [Errno 11] Resource temporarily unavailable
, 22:42:46.113840)
ERROR: Unable to connect to bitbake server, or start one (server startup failures would be in bitbake-cookerdaemon.log).
make: *** [Makefile:113: feed] Error 1
elhawary@elhawary-MS-7848:~/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
You have problem with bitbake ... Check build folder and if you see lock file remove and try again ..
