### ISSUE TITLE
{pd1loi-hd-night}->>This is not currently available

### ISSUE THREAD

**Issue by atefganm** [fairbird/openpli-dreambox-oe-core#86]
check internet connection: Online      
Loading cache: 100% |##########################################################################################################################################################################################################################| Time: 0:00:01
Loaded 5094 entries from dependency cache.
WARNING: /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pd1loi-hd-night.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc            | ETA:  0:00:07
WARNING: /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pd1loi-hd-night.bb: Error during finalise of /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pd1loi-hd-night.bb
ERROR: ExpansionError during parsing /home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2-skins/enigma2-plugin-skins-pd1loi-hd-night.bb
Traceback (most recent call last):
  File "/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1244, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f78c54185b0>, d=<bb.data_smart.DataSmart object at 0x7f78bd74efe0>, name='default'):
             d.setVar("__BBAUTOREV_ACTED_UPON", True)
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 1660, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f78c54185b0>, d=<bb.data_smart.DataSmart object at 0x7f78bd74efe0>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 806, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f78c54185b0>, d=<bb.data_smart.DataSmart object at 0x7f78bd74efe0>, name='default'):
     
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/git.py", line 789, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f78c54185b0>, d=<bb.data_smart.DataSmart object at 0x7f78bd74efe0>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/lib/bb/fetch2/__init__.py", line 957, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="2838"; export SSH_AUTH_SOCK="/tmp/ssh-XXXXXXhFXiOv/agent.2837"; export PATH="/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/openembedded-core/scripts:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/usr/bin/allarch-oe-linux:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot/usr/bin/crossscripts:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/usr/sbin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/usr/bin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/sbin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/bin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/bin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/atef"; git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all ls-remote https://github.com/PD1LOI/Pd1loi-HD-night.git ', d=<bb.data_smart.DataSmart object at 0x7f78bd74efe0>, quiet=True, cleanup=[], log=None, workdir=None):
     
    >        raise FetchError(error_message)
     
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="2838"; export SSH_AUTH_SOCK="/tmp/ssh-XXXXXXhFXiOv/agent.2837"; export PATH="/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/openembedded-core/scripts:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/usr/bin/allarch-oe-linux:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot/usr/bin/crossscripts:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/usr/sbin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/usr/bin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/sbin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-skins-pd1loi-hd-night/2.6.1+git/recipe-sysroot-native/bin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/bitbake/bin:/home/atef/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core/build/tmp/hosttools"; export HOME="/home/atef"; git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all ls-remote https://github.com/PD1LOI/Pd1loi-HD-night.git  failed with exit code 128, output:
fatal: could not read Username for 'https://github.com': No such device or address

The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above

Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:109: image] Error 1
atef@atef-ganm:~/fairbird-openpli-dreambox-oe-core/openpli-dreambox-oe-core$

**Comment by fairbird** [comment]
Removed !! Account offline.
https://github.com/fairbird/openpli-dreambox-oe-core/commit/98ad1577f0ff85e7c5f7d1b87a5f09db23fb7cd3
